run:
  timeout: 3m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple  
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
  disable-all: false

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 50